import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
export type CalendarEntry={id?:string;staff_id:number;appointment_date:string;start_minute:number;duration:number;show_as:string;description:string;revision:number};
const time=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const minutes=(s:string)=>{const [h,m]=s.split(':').map(Number);return h*60+m;};
export function useCalendarEntries(db:SupabaseClient|null,date:string,staff:{id:number;name:string}[],own:number|null,admin:boolean){
 const [entries,setEntries]=useState<CalendarEntry[]>([]),[draft,setDraft]=useState<CalendarEntry|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0);
 useEffect(()=>{let active=true;setEntries([]);if(db)void db.from('staff_calendar_entries').select('*').eq('appointment_date',date).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setEntries(data||[]);});return()=>{active=false;};},[db,date,version]);
 function open(e?:CalendarEntry){setError('');setDraft(e?{...e}:{staff_id:own||staff[0]?.id,appointment_date:date,start_minute:540,duration:60,show_as:'busy',description:'',revision:0});}
 async function save(remove=false){if(!db||!draft||busy)return;setBusy(true);setError('');try{const r=await db.rpc('save_calendar_entry',{p_staff:draft.staff_id,p_date:draft.appointment_date,p_start:draft.start_minute,p_end:draft.start_minute+draft.duration,p_show:draft.show_as,p_description:draft.description,p_id:draft.id||null,p_revision:draft.revision,p_delete:remove});if(r.error)throw r.error;setDraft(null);setVersion(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const dialog=draft&&<div className="modal-backdrop"><section className="panel modal" role="dialog" aria-modal="true" aria-label="Calendar entry"><h2>{draft.id?'Edit Calendar Entry':'Block Out Time'}</h2><form onSubmit={e=>{e.preventDefault();void save();}}><label>Staff Member<select disabled={busy||!admin} value={draft.staff_id} onChange={e=>setDraft({...draft,staff_id:Number(e.target.value)})}>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Date<input type="date" required disabled={busy} value={draft.appointment_date} onChange={e=>setDraft({...draft,appointment_date:e.target.value})}/></label><label>Start Time<input type="time" required disabled={busy} value={time(draft.start_minute)} onChange={e=>{const start=minutes(e.target.value);setDraft({...draft,start_minute:start,duration:draft.start_minute+draft.duration-start});}}/></label><label>End Time<input type="time" required disabled={busy} value={time(draft.start_minute+draft.duration)} onChange={e=>setDraft({...draft,duration:minutes(e.target.value)-draft.start_minute})}/></label><label>Show as Busy/Free<select disabled={busy} value={draft.show_as} onChange={e=>setDraft({...draft,show_as:e.target.value})}><option value="busy">Busy</option><option value="free">Free</option></select></label><label>Description<textarea required maxLength={500} disabled={busy} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>{error&&<p role="alert" className="auth-error">{error}</p>}<div className="record-actions"><button className="primary" disabled={busy}>Save</button><button type="button" className="secondary" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button>{draft.id&&<button type="button" className="danger" disabled={busy} onClick={()=>void save(true)}>Delete Calendar Entry</button>}</div></form></section></div>;
 return {entries,open,dialog};
}
