import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Row={id:string;recorded_at:string;client_name:string;client_email:string;treatment_name:string;original_price:number;discounted_price:number;discount_percentage:number;staff_name:string};
const headings=['Date/Time','Client Name','Client Email','Treatment Name','Original Price','Discounted Price','Discount %','Staff Name'];
const date=(s:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Dublin',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(s)).replace(',','');
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n);
export default function DiscountsReport({db,onBack}:{db:SupabaseClient|null;onBack:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[staff,setStaff]=useState<{id:number;name:string}[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[person,setPerson]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[latest,setLatest]=useState(true);
 async function load(initial=false){if(!db){setError('Connect to Supabase to generate this report.');return;}if(!initial&&(!from||!to||from>to)){setError('Choose a valid From and To date.');return;}setBusy(true);setError('');try{const r=await db.rpc('get_discounts_report',{p_from:initial?null:from,p_to:initial?null:to,p_staff:person?Number(person):null});if(r.error)throw r.error;setRows(r.data||[]);setLatest(initial);}catch(e){setError((e as Error).message);setRows([]);}finally{setBusy(false);}}
 useEffect(()=>{void load(true);if(db)void db.rpc('get_discount_report_staff').then(({data,error})=>{if(error)setError(error.message);else setStaff(data||[]);});},[db]);
 const cells=(r:Row,csv=false)=>[date(r.recorded_at),r.client_name,r.client_email,r.treatment_name,csv?Number(r.original_price).toFixed(2):money(Number(r.original_price)),csv?Number(r.discounted_price).toFixed(2):money(Number(r.discounted_price)),Number(r.discount_percentage).toFixed(2)+(csv?'':'%'),r.staff_name];
 function download(){const csv=[headings,...rows.map(r=>cells(r,true))].map(row=>row.map(v=>{let s=String(v??'');if(/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='discounts-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel"><button className="back" onClick={onBack}>← Reporting</button><h1>Discounts Report</h1><form onSubmit={e=>{e.preventDefault();void load();}}><div className="report-filters"><label>From Date<input type="date" value={from} disabled={busy} onChange={e=>setFrom(e.target.value)}/></label><label>To Date<input type="date" value={to} disabled={busy} onChange={e=>setTo(e.target.value)}/></label><label>Staff Name<select value={person} disabled={busy} onChange={e=>setPerson(e.target.value)}><option value="">All staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><button className="primary" disabled={busy}>Generate</button><button type="button" className="back" disabled={busy} onClick={()=>void load(true)}>Latest 25 discounts</button></form><p className="small">{latest?'Latest 25 discounts':'Discounts in the selected date range'} · Dates show when the discount was saved, in Dublin time.</p>{error&&<p role="alert" className="auth-error">{error}</p>}{busy?<p>Loading…</p>:<><button className="secondary" disabled={!rows.length} onClick={download}>Export to CSV</button>{rows.length?<div className="table-scroll"><table><thead><tr>{headings.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cells(r).map((c,i)=><td key={i}>{c}</td>)}</tr>)}</tbody></table></div>:<p>No discounts found.</p>}</>}</section>;
}
